# Change these first
owner: ZarzueloM # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Validaciones Online
    url: https://colmed.tandemdigital.net
  - name: Colmed Web
    url: https://www.colmedsanjuan.com.ar
    icon: https://www.colmedsanjuan.com.ar/intranet/favicon.ico
  #- name: Validfarma
  #  url: https://sdf.tandemdigital.net
 #   icon: https://sdf.tandemdigital.net/assets/favicon.ico
assignees:
  - ZarzueloM
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.colmedsanjuan.com.ar 
  #demo.upptime.js.org
  #baseUrl: /status
  logoUrl: https://colmedsanjuan.com.ar/assets/img/logo.png
  name: Status
  introTitle: "COLMED - Página de estados."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
